<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x64</Platforms>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<EnableMicrosoftExtensionsDependencyInjectionSourceGenerator>true</EnableMicrosoftExtensionsDependencyInjectionSourceGenerator>
	</PropertyGroup>
	<ItemGroup>
		<TrimmerRootDescriptor Include="TrimmerRoots.xml" />
		<TrimmerRootAssembly Include="Avalonia.Themes.Fluent" />
		<TrimmerRootAssembly Include="Avalonia.Controls" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\OneLauncher.Console\OneLauncher.Console.csproj" />
		<ProjectReference Include="..\OneLauncher\OneLauncher.csproj" />
	</ItemGroup>
	<PropertyGroup>
		<ApplicationIcon>window-logo.ico</ApplicationIcon>
	</PropertyGroup>
	<Target Name="RemoveSymbolsFromPublish"
			AfterTargets="Publish"
			Condition="'$(Configuration)' == 'Release'">
		<ItemGroup>
			<PublishedSymbols Include="$(PublishDir)**\*.pdb" />
		</ItemGroup>
		<Delete Files="@(PublishedSymbols)" />
	</Target>
</Project>
